export enum RolUsuario {
  ADMINISTRADOR = 'ADMINISTRADOR',
  GESTOR_SOLICITUDES = 'GESTOR_SOLICITUDES',
}

export enum EstadoSolicitud {
  PENDIENTE = 'PENDIENTE',
  APROBADA = 'APROBADA',
  RECHAZADA = 'RECHAZADA',
  ASIGNADA = 'ASIGNADA',
  DESPACHADA = 'DESPACHADA',
  COMPLETADA = 'COMPLETADA',
  CANCELADA = 'CANCELADA',
}