import swaggerJSDoc from 'swagger-jsdoc';

const id = { in: 'path', name: 'id', required: true, schema: { type: 'integer' } };
const auth = [{ bearerAuth: [] }];
const secured = { 401: { description: 'Token requerido o inválido' }, 403: { description: 'Rol no autorizado' }, 404: { description: 'Recurso no encontrado' } };
const request = (schema: string) => ({ required: true, content: { 'application/json': { schema: { $ref: `#/components/schemas/${schema}` } } } });

export const swaggerSpec = swaggerJSDoc({
  definition: {
    openapi: '3.0.3',
    info: { title: 'RiwiMediCare API', version: '1.0.0', description: 'API REST para la gestión de solicitudes de abastecimiento de medicamentos.' },
    servers: [{ url: 'http://localhost:3000', description: 'Servidor local' }],
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
      schemas: {
        UsuarioRegistro: { type: 'object', required: ['nombre', 'email', 'password', 'rol'], properties: { nombre: { type: 'string', example: 'Administrador Principal' }, email: { type: 'string', format: 'email', example: 'admin@riwimedicare.com' }, password: { type: 'string', format: 'password', example: 'ClaveSegura123' }, rol: { type: 'string', enum: ['ADMINISTRADOR', 'GESTOR_SOLICITUDES'] } } },
        Clinica: { type: 'object', required: ['nombre', 'nit', 'direccion'], properties: { nombre: { type: 'string', example: 'Clinica Norte' }, nit: { type: 'string', example: '901234567-8' }, direccion: { type: 'string', example: 'Carrera 20 # 15-10' }, telefono: { type: 'string', example: '3015555555' }, email: { type: 'string', format: 'email' } } },
        Almacen: { type: 'object', required: ['nombre', 'direccion'], properties: { nombre: { type: 'string', example: 'Almacen Central' }, direccion: { type: 'string', example: 'Avenida 30 # 45-20' } } },
        Medicamento: { type: 'object', required: ['nombre', 'codigo', 'unidad_medida'], properties: { nombre: { type: 'string', example: 'Acetaminofen 500 mg' }, codigo: { type: 'string', example: 'MED-ACET-500' }, descripcion: { type: 'string' }, presentacion: { type: 'string' }, unidad_medida: { type: 'string', example: 'TABLETA' } } },
        Inventario: { type: 'object', required: ['almacen_id', 'medicamento_id', 'cantidad_disponible'], properties: { almacen_id: { type: 'integer', example: 1 }, medicamento_id: { type: 'integer', example: 1 }, cantidad_disponible: { type: 'integer', minimum: 0, example: 100 }, stock_minimo: { type: 'integer', minimum: 0, example: 20 } } },
        Solicitud: { type: 'object', required: ['clinica_id', 'almacen_asignado_id', 'detalles'], properties: { clinica_id: { type: 'integer', example: 1 }, almacen_asignado_id: { type: 'integer', example: 1 }, observaciones: { type: 'string' }, detalles: { type: 'array', items: { type: 'object', required: ['medicamento_id', 'cantidad_solicitada'], properties: { medicamento_id: { type: 'integer', example: 1 }, cantidad_solicitada: { type: 'integer', minimum: 1, example: 20 }, observaciones: { type: 'string' } } } } } },
        Estado: { type: 'object', required: ['estado'], properties: { estado: { type: 'string', enum: ['PENDIENTE', 'APROBADA', 'RECHAZADA', 'ASIGNADA', 'DESPACHADA', 'COMPLETADA', 'CANCELADA'], example: 'APROBADA' }, observacion: { type: 'string' } } },
      },
    },
    paths: {
      '/health': { get: { tags: ['Sistema'], summary: 'Verifica el estado de la API', responses: { 200: { description: 'API disponible' } } } },
      '/auth/register': { post: { tags: ['Autenticación'], summary: 'Registra un usuario', requestBody: request('UsuarioRegistro'), responses: { 201: { description: 'Usuario creado' }, 400: { description: 'Datos inválidos' }, 409: { description: 'Correo duplicado' } } } },
      '/auth/login': { post: { tags: ['Autenticación'], summary: 'Inicia sesión y retorna JWT', requestBody: { required: true, content: { 'application/json': { example: { email: 'admin@riwimedicare.com', password: 'ClaveSegura123' } } } }, responses: { 200: { description: 'Inicio de sesión exitoso' }, 401: { description: 'Credenciales inválidas' } } } },
      '/clinicas': { get: { tags: ['Clínicas'], summary: 'Lista clínicas', security: auth, responses: { 200: { description: 'Lista de clínicas' }, ...secured } }, post: { tags: ['Clínicas'], summary: 'Crea clínica', security: auth, requestBody: request('Clinica'), responses: { 201: { description: 'Clínica creada' }, 409: { description: 'NIT duplicado' }, ...secured } } },
      '/clinicas/{id}': { get: { tags: ['Clínicas'], summary: 'Consulta clínica', security: auth, parameters: [id], responses: { 200: { description: 'Clínica encontrada' }, ...secured } }, patch: { tags: ['Clínicas'], summary: 'Actualiza clínica', security: auth, parameters: [id], requestBody: request('Clinica'), responses: { 200: { description: 'Clínica actualizada' }, ...secured } }, delete: { tags: ['Clínicas'], summary: 'Desactiva clínica', security: auth, parameters: [id], responses: { 200: { description: 'Clínica desactivada' }, ...secured } } },
      '/clinicas/{id}/responsables': { post: { tags: ['Clínicas'], summary: 'Asigna responsable', security: auth, parameters: [id], requestBody: { required: true, content: { 'application/json': { example: { usuario_id: 1 } } } }, responses: { 201: { description: 'Responsable asignado' }, 409: { description: 'Asociación duplicada' }, ...secured } } },
      '/almacenes': { get: { tags: ['Almacenes'], summary: 'Lista almacenes', security: auth, responses: { 200: { description: 'Lista de almacenes' }, ...secured } }, post: { tags: ['Almacenes'], summary: 'Crea almacén', security: auth, requestBody: request('Almacen'), responses: { 201: { description: 'Almacén creado' }, ...secured } } },
      '/almacenes/{id}': { get: { tags: ['Almacenes'], summary: 'Consulta almacén', security: auth, parameters: [id], responses: { 200: { description: 'Almacén encontrado' }, ...secured } }, patch: { tags: ['Almacenes'], summary: 'Actualiza almacén', security: auth, parameters: [id], requestBody: request('Almacen'), responses: { 200: { description: 'Almacén actualizado' }, ...secured } }, delete: { tags: ['Almacenes'], summary: 'Desactiva almacén', security: auth, parameters: [id], responses: { 200: { description: 'Almacén desactivado' }, ...secured } } },
      '/medicamentos': { get: { tags: ['Medicamentos'], summary: 'Lista medicamentos', security: auth, responses: { 200: { description: 'Lista de medicamentos' }, ...secured } }, post: { tags: ['Medicamentos'], summary: 'Crea medicamento', security: auth, requestBody: request('Medicamento'), responses: { 201: { description: 'Medicamento creado' }, 409: { description: 'Código duplicado' }, ...secured } } },
      '/medicamentos/{id}': { get: { tags: ['Medicamentos'], summary: 'Consulta medicamento', security: auth, parameters: [id], responses: { 200: { description: 'Medicamento encontrado' }, ...secured } }, patch: { tags: ['Medicamentos'], summary: 'Actualiza medicamento', security: auth, parameters: [id], requestBody: request('Medicamento'), responses: { 200: { description: 'Medicamento actualizado' }, ...secured } }, delete: { tags: ['Medicamentos'], summary: 'Desactiva medicamento', security: auth, parameters: [id], responses: { 200: { description: 'Medicamento desactivado' }, ...secured } } },
      '/inventarios': { get: { tags: ['Inventarios'], summary: 'Lista inventarios', security: auth, responses: { 200: { description: 'Inventarios con relaciones' }, ...secured } }, post: { tags: ['Inventarios'], summary: 'Crea inventario', security: auth, requestBody: request('Inventario'), responses: { 201: { description: 'Inventario creado' }, 409: { description: 'Inventario duplicado' }, ...secured } } },
      '/inventarios/{id}': { get: { tags: ['Inventarios'], summary: 'Consulta inventario', security: auth, parameters: [id], responses: { 200: { description: 'Inventario encontrado' }, ...secured } }, patch: { tags: ['Inventarios'], summary: 'Actualiza inventario', security: auth, parameters: [id], requestBody: request('Inventario'), responses: { 200: { description: 'Inventario actualizado' }, ...secured } } },
      '/solicitudes': { post: { tags: ['Solicitudes'], summary: 'Crea solicitud de abastecimiento', security: auth, requestBody: request('Solicitud'), responses: { 201: { description: 'Solicitud creada' }, 400: { description: 'Inventario insuficiente o datos inválidos' }, ...secured } } },
      '/solicitudes/activas': { get: { tags: ['Solicitudes'], summary: 'Lista solicitudes activas', security: auth, responses: { 200: { description: 'Solicitudes no finalizadas' }, ...secured } } },
      '/solicitudes/clinica/{clinicaId}/historial': { get: { tags: ['Solicitudes'], summary: 'Consulta historial por clínica', security: auth, parameters: [{ ...id, name: 'clinicaId' }], responses: { 200: { description: 'Historial por clínica' }, ...secured } } },
      '/solicitudes/historial-completo': { get: { tags: ['Solicitudes'], summary: 'Consulta historial completo', security: auth, responses: { 200: { description: 'Historial completo' }, ...secured } } },
      '/solicitudes/{id}': { get: { tags: ['Solicitudes'], summary: 'Consulta solicitud', security: auth, parameters: [id], responses: { 200: { description: 'Solicitud con relaciones' }, ...secured } } },
      '/solicitudes/{id}/estado': { patch: { tags: ['Solicitudes'], summary: 'Cambia estado según el flujo permitido', security: auth, parameters: [id], requestBody: request('Estado'), responses: { 200: { description: 'Estado actualizado e historial creado' }, 400: { description: 'Transición no permitida' }, ...secured } } },
      '/solicitudes/{id}/asignar': { patch: { tags: ['Solicitudes'], summary: 'Asigna almacén a solicitud aprobada', security: auth, parameters: [id], requestBody: { required: true, content: { 'application/json': { example: { almacen_asignado_id: 1, observacion: 'Asignada al almacén central' } } } }, responses: { 200: { description: 'Solicitud asignada' }, 400: { description: 'Estado o inventario no válido' }, ...secured } } },
      '/seed/json': { post: { tags: ['Seeder'], summary: 'Carga datos desde archivo JSON', security: auth, requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: ['archivo'], properties: { archivo: { type: 'string', format: 'binary' } } } } } }, responses: { 201: { description: 'Archivo procesado' }, 400: { description: 'Archivo o JSON inválido' }, ...secured } } },
    },
  },
  apis: [],
});